import type { Transaction, Category, User } from "@/lib/types";

export const mockUser: User = {
  id: "1",
  name: "Alex Morgan",
  email: "alex.morgan@example.com",
};

export const mockCategories: Category[] = [
  { id: "1", name: "Salary", type: "income" },
  { id: "2", name: "Freelance", type: "income" },
  { id: "3", name: "Investments", type: "income" },
  { id: "4", name: "Rent", type: "expense" },
  { id: "5", name: "Groceries", type: "expense" },
  { id: "6", name: "Utilities", type: "expense" },
  { id: "7", name: "Entertainment", type: "expense" },
  { id: "8", name: "Transport", type: "expense" },
];

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    title: "Monthly Salary",
    amount: 5200,
    type: "income",
    categoryId: "1",
    date: "2026-02-01",
    description: "February salary payment",
  },
  {
    id: "2",
    title: "Freelance Project",
    amount: 1500,
    type: "income",
    categoryId: "2",
    date: "2026-02-05",
    description: "Logo design for client",
  },
  {
    id: "3",
    title: "Apartment Rent",
    amount: 1800,
    type: "expense",
    categoryId: "4",
    date: "2026-02-01",
    description: "Monthly rent for February",
  },
  {
    id: "4",
    title: "Grocery Shopping",
    amount: 320,
    type: "expense",
    categoryId: "5",
    date: "2026-02-03",
    description: "Weekly groceries",
  },
  {
    id: "5",
    title: "Electric Bill",
    amount: 145,
    type: "expense",
    categoryId: "6",
    date: "2026-02-07",
    description: "Monthly electricity",
  },
  {
    id: "6",
    title: "Dividend Income",
    amount: 380,
    type: "income",
    categoryId: "3",
    date: "2026-02-10",
    description: "Q1 dividend payout",
  },
  {
    id: "7",
    title: "Movie Tickets",
    amount: 45,
    type: "expense",
    categoryId: "7",
    date: "2026-02-12",
    description: "Weekend movies",
  },
  {
    id: "8",
    title: "Metro Pass",
    amount: 90,
    type: "expense",
    categoryId: "8",
    date: "2026-02-01",
    description: "Monthly metro pass",
  },
  {
    id: "9",
    title: "Freelance Consulting",
    amount: 800,
    type: "income",
    categoryId: "2",
    date: "2026-01-20",
    description: "Consulting for startup",
  },
  {
    id: "10",
    title: "January Salary",
    amount: 5200,
    type: "income",
    categoryId: "1",
    date: "2026-01-01",
    description: "January salary payment",
  },
  {
    id: "11",
    title: "Internet Bill",
    amount: 75,
    type: "expense",
    categoryId: "6",
    date: "2026-01-15",
    description: "Monthly internet bill",
  },
  {
    id: "12",
    title: "Restaurant Dinner",
    amount: 120,
    type: "expense",
    categoryId: "7",
    date: "2026-01-18",
    description: "Birthday dinner",
  },
];
